version: '3.9'
services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data/
    # Les ports ne doivent pas être exposés en production pour des raisons de sécurité
    # ports:
    #   - '5432:5432'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    # Utiliser Gunicorn ou un autre serveur WSGI pour la production au lieu de runserver
    command: gunicorn pzt_api.wsgi:application --bind 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '8000:8000'
    # Les volumes de développement peuvent être retirés en production
    # volumes:
    #   - .:/api
    depends_on:
      - postgres-db

  # PgAdmin n'est généralement pas nécessaire en production, à moins que vous n'ayez besoin de gestion de base de données
  # pg-admin:
  #   ...

volumes:
  postgres:
  # my-data: (si vous utilisez PgAdmin)
